### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by cyulin17** [cyulin17/final-project#1]
## ⚙️ Feature

> ##### Users can set the date of the trip and start planning. 

## 📐 Functionality

> ##### Users can set the date of the trip and start planning.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Home Page](https://user-images.githubusercontent.com/78944582/142269330-d339b406-6fb3-4c34-a77f-9f194a83a6ce.png)
![Home Page - mobile](https://user-images.githubusercontent.com/78944582/142277101-04848e96-c095-43b0-85ce-2f8d064e53ca.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Set up react-hash-routing
- [x] Create database.
- [x] Install bootstrap
- [x] Create a nav bar
- [x] Create a react carousel for displaying the photos.
- [x] Create a planning bar.
- [x] Pick 2-3 photos.
